version: "3"
services:
  registry2:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
    volumes:
      - .data:/var/lib/registry
